version: '3.8'
services:
  zookeeper-dev:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper-dev
    container_name: zookeeper-dev
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-dev-data:/var/lib/zookeeper/data
      - zookeeper-dev-logs:/var/lib/zookeeper/log

  kafka-dev:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka-dev
    container_name: kafka-dev
    depends_on:
      - zookeeper-dev
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-dev:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-dev:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      # Настройки для разработки
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
    volumes:
      - kafka-dev-data:/var/lib/kafka/data

  kafka-ui-dev:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-dev
    depends_on:
      - kafka-dev
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: development
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-dev:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-dev:2181
      KAFKA_CLUSTERS_0_READONLY: false

volumes:
  zookeeper-dev-data:
  zookeeper-dev-logs:
  kafka-dev-data:
