version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: zameni-postgres
    environment:
      POSTGRES_DB: zameni_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Redis для кеширования (опционально)
  redis:
    image: redis:7-alpine
    container_name: zameni-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
