name: Rollback Job

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash to rollback to'
        required: true
        type: string
      environment:
        description: 'Environment to rollback'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
        - development

jobs:
  rollback:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.commit_hash }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build application
      run: npm run build
      
    - name: Rollback to commit ${{ github.event.inputs.commit_hash }}
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/zameni-api
          
          # Сохраняем текущий коммит
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "Current commit: $CURRENT_COMMIT"
          
          # Переключаемся на указанный коммит
          git checkout ${{ github.event.inputs.commit_hash }}
          
          # Перезапускаем с новой версией
          docker-compose -f docker-compose.${{ github.event.inputs.environment }}.yml down
          docker-compose -f docker-compose.${{ github.event.inputs.environment }}.yml up -d --build
          
    - name: Health check
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sleep 30
          curl -f https://${{ secrets.DOMAIN }}/health || exit 1
          
    - name: Notify rollback
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          🔄 Rollback completed!
          
          ⚠️ Zameni API rolled back to commit ${{ github.event.inputs.commit_hash }}
          🌍 Environment: ${{ github.event.inputs.environment }}
          🌐 Domain: ${{ secrets.DOMAIN }}
          📚 Docs: https://${{ secrets.DOMAIN }}/docs
          💚 Health: https://${{ secrets.DOMAIN }}/health
